import ReduxProvider from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import NextAuth from './providers/sessionProvider'
import SingButton from '@/components/Header/Header'
import Header from '@/components/Header/Header'
config.autoAddCss = false
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      />
      <body className={inter.className}>
        <ReduxProvider>
          <NextAuth>
            <Header />
            {children}
          </NextAuth>
        </ReduxProvider>
      </body>
    </html>
  )
}
